Repository AY2324S1-CS2103T-T12-1/tp, pull requests merged in 2023-10, with the labels that each got.

#32 Update the Ui.png
  docs/images/Ui.png
  docs/images/johndoe.png
  docs/images/proto-aiken-13.png
Labels: priority.High

#33 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: priority.High

#35 Fix PPP names
  docs/team/choonyan02.md
  docs/team/et-irl.md
  docs/team/lsyurea.md
  docs/team/proto-aiken-13.md
  docs/team/vanessamae23.md
Labels: priority.High

#61 Update UserGuide.md, Add Mark and Unmark Attendance feature
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/UnmarkAttendanceParser.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAttendanceParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/UnmarkAttendanceParserTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#56 Change address to telegram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/TelegramHandleTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#65 Update Test Coverage
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/fields/CommentTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
Labels: priority.High

#70 Add telegram link
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement

#78 Update Help Command
  docs/DeveloperGuide.md
  docs/team/lsyurea.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#85 Add the grade command for the assignments
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/vanessamae23.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/GradeCommandParser.java
  src/main/java/seedu/address/model/person/Assignment.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/GradeCommandTest.java
  src/test/java/seedu/address/logic/parser/GradeCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High

#92 Fixed saving assignment grades
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignmentCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/model/person/Assignment.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/resources/images/npctrack.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#99 Update the User Guide
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_layouts/default.html
  docs/assets/css/style.scss
  docs/images/npctrack-guide.png
  docs/images/ug-image.png
Labels: priority.Low

#98 Create group command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/lsyurea.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignmentCommand.java
  src/main/java/seedu/address/logic/commands/CreateGroupCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/GradeCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/CreateGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Group.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/CreateGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High

#115 Update Attendance.java
  src/main/java/seedu/address/model/person/Attendance.java
Labels: priority.High

#117 Unmark group branch
  docs/UserGuide.md
  docs/team/lsyurea.md
  src/main/java/seedu/address/logic/commands/UnmarkGroupAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UnmarkGroupAttendanceParser.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#130 Update findGroup command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/lsyurea.md
  src/main/java/seedu/address/logic/commands/FindGroupCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindGroupCommandParser.java
  src/main/java/seedu/address/model/person/GroupContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindGroupCommandTest.java
  src/test/java/seedu/address/logic/parser/FindGroupCommandParserTest.java
Labels: priority.Medium

#135 Fix Terse English in User Guide
  docs/UserGuide.md
  docs/team/et-irl.md
Labels: easy

#134 Rename Open Telegram Link Method
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: easy

#139 Update DG on UML diagram for inputPP
  docs/DeveloperGuide.md
  docs/diagrams/InputParticipationSequenceDiagram.puml
  docs/images/InputParticipationSequenceDiagram.png
  docs/team/choonyan02.md
  src/test/java/seedu/address/logic/commands/InputParticipationCommandTest.java
  src/test/java/seedu/address/logic/commands/ListParticipationCommandTest.java
Labels: easy

#144 Add ConfirmClearCommand
  docs/UserGuide.md
  docs/team/choonyan02.md
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ConfirmClearCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/ConfirmClearCommandTest.java
Labels: priority.Medium

#150 Add inputGroupPP command
  docs/UserGuide.md
  docs/team/choonyan02.md
  src/main/java/seedu/address/logic/commands/InputGroupParticipationCommand.java
  src/main/java/seedu/address/logic/commands/InputParticipationCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/InputGroupParticipationParser.java
  src/test/java/seedu/address/logic/commands/InputGroupParticipationCommandTest.java
  src/test/java/seedu/address/logic/parser/InputGroupParticipationParserTest.java
Labels: priority.Medium

#147 Update regex for telegram
  docs/UserGuide.md
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/model/person/TelegramHandle.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/TelegramHandleTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#155 Refactor opening telegram to UiUtil
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiUtil.java
Labels: easy

#157 Make sane examples
  docs/UserGuide.md
  docs/team/et-irl.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/GradeGroupCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: easy

#160 Refactor openUserGuide() to fit with OOP principles
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiUtil.java
Labels: easy

#164 Improve error handling
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/GradeCommandParser.java
  src/main/java/seedu/address/logic/parser/GradeGroupCommandParser.java
  src/test/java/seedu/address/logic/parser/GradeCommandParserTest.java
  src/test/java/seedu/address/logic/parser/GradeGroupCommandParserTest.java
Labels: priority.High

#178 Fix group attendance marking bug
  src/main/java/seedu/address/logic/commands/MarkGroupAttendanceCommand.java
Labels: easy
