Repository AY2324S1-CS2103T-T12-1/tp, pull requests merged in 2023-11, with the labels that each got.

#231 Fix documentation for `findGroup`
  docs/UserGuide.md
Labels: easy

#234 Fix missing backticks in table of contents
  docs/UserGuide.md
Labels: easy

#228 Fix edit error message
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: easy

#227 Fix duplicate entries in the common parameters section
  docs/UserGuide.md
Labels: easy

#236 Fix numbering
  docs/DeveloperGuide.md
Labels: easy

#237 Relink User Guide URL
  src/main/java/seedu/address/ui/UiUtil.java
Labels: easy

#187 Refactor `arePrefixesPresent` into `ParserUtil`
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignmentGroupCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignmentIndivCommandParser.java
  src/main/java/seedu/address/logic/parser/DeassignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeassignmentIndivCommandParser.java
  src/main/java/seedu/address/logic/parser/InputGroupParticipationParser.java
  src/main/java/seedu/address/logic/parser/InputParticipationParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: easy

#230 Fix grammar and stylisation issues.
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AssignmentGroupCommand.java
Labels: easy

#229 Add name case insensitivity for `Person`s `Name`.
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: needs discussion

#248 Fix InputGroupParticipationCommand
  docs/UserGuide.md
  docs/diagrams/InputParticipationSequenceDiagram.puml
  docs/images/InputParticipationSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/InputGroupParticipationCommand.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/test/java/seedu/address/logic/commands/InputGroupParticipationCommandTest.java
  src/test/java/seedu/address/logic/parser/InputGroupParticipationParserTest.java
  src/test/java/seedu/address/logic/parser/InputParticipationParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAttendanceParserTest.java
  src/test/java/seedu/address/logic/parser/UnmarkAttendanceParserTest.java
Labels: priority.Medium

#256 Update UG about find command keyword
  docs/UserGuide.md
Labels: priority.Low

#255 Add assignment test and update UG to state case sensitivity of Assignment
  docs/UserGuide.md
  docs/team/vanessamae23.md
  src/test/java/seedu/address/model/person/AssignmentTest.java
Labels: priority.Medium

#253 Change filename from addressbook to npctrack
  build.gradle
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: priority.Low

#285 Create assignment and group assignment test
  src/main/java/seedu/address/logic/commands/AssignmentGroupCommand.java
  src/test/java/seedu/address/logic/commands/AssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignmentGroupCommandTest.java
Labels: priority.Medium
